apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-project
  namespace: default
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: sample-dev
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"