apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: superapp-controller-knp
  labels:
    strimzi.io/cluster: superapp-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 5Gi
    deleteClaim: false