apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-dev

resources:
  - ../../../base/kafka

nameSuffix: -dev

# Example prod override (optional)
# patches:
#   - target:
#       kind: KafkaNodePool
#     patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 1

# Ensure KafkaNodePool labels reference the suffixed cluster name
patches:
  - target:
      kind: KafkaNodePool
    patch: |-
      - op: replace
        path: /metadata/labels/strimzi.io~1cluster
        value: superapp-cluster-dev