apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-kafka-dev
  namespace: default
spec:
  project: sample-project
  sources:
    - repoURL: https://github.com/zele26/gitops-sample-example.git
      targetRevision: HEAD
      path: k8s-manifests/overlays/dev/kafka
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true